name: CI

on:
  push:
    branches:
    - master
    - solutions
  schedule:
  - cron: 0 0 * * 1-5

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: mvn -B package
